config/routes.rb
Rails.application.routes.draw do

#   -- static_pages --

  root 'static_pages#home'
  get 'static_pages/home'

  #    -- Sessions --

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  #    -- Users --

  resources :users

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

#   - Events -

  resources :events

  get 'events/:id/participe/', to: 'events#participe', as: 'subscribe'
  get 'events/:id/unfollow', to: 'events#unfollow', as: 'unfollow'
  # get 'events/:id/attendees/', to: 'events#showattendees', as: 'attendees'
  get '/new-event', to: 'events#new'
  post '/new-event', to: 'events#create'
  get '/all-events', to: 'events#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

# Source : http://guides.rubyonrails.org/association_basics.html#the-has-and-belongs-to-many-association
belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
has_and_belongs_to_many :attendees, class_name: "User"

validates :title, presence: true
validates :description, presence: true
validates :date, presence: true
validates :place, presence: true

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }

  validates :password, presence: true,
                       length: { minimum: 6 }

 # Source : http://guides.rubyonrails.org/association_basics.html#the-has-and-belongs-to-many-association
  has_many :created_events, class_name: "Event"
	has_and_belongs_to_many :attended_events, class_name: "Event"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def create
    @event = Event.new(event_params)
    @event.creator = current_user

    if @event.save
      flash[:success] = "Evenement créé avec succès ! "
       redirect_to @event
    else
      flash.now[:danger] = "Veuillez complèter tous les champs"
       render 'new'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  def edit
    @event = Event.find(params[:id])
  end

  def index
    @events = Event.all
  end

  def new
      @event = Event.new
  end

  def participe
    @event = Event.find(params[:id])
    if
      @event.attendees.include? current_user
      flash[:warning] = "Vous êtes déjà inscrit"
      redirect_to @event
    else
      @event.attendees << current_user
      flash[:success] = "Félicitation, vous participez à l'événement !"
      redirect_to @event
    end
  end

  def unfollow     #  https://ruby-doc.org/core-1.9.3/Array.html#method-i-delete
    @event = Event.find(params[:id])
    @event.attendees.delete(current_user)
    redirect_to current_user
    flash[:warning] = "Vous ne suivez plus cet évenement."

  end

  # def showattendees
  #   @attendees = Event.users.attendees.all
  # end

  def show
    @event = Event.find(params[:id])
  end


  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:success] = "Event mis à jour"
      redirect_to @event
    else
      render 'edit'
    end
  end


  private

  def event_params
    params.require(:event).permit(:title, :description, :date, :place)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(email: params[:session][:email])
      if user && user.authenticate(params[:session][:password])
        log_in(user)
        flash[:success] = "Bienvenue sur EventBrite"
        redirect_to user
      else
        flash.now[:danger] = "Mauvaise combinaison email/password"
        render 'new'
      end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

  def new
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Connexion avec succès le #{Date.today}"
       redirect_to @user
    else
       render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def new
    if logged_in?
      @user = User.new
    else
      @user = User.new
      flash.now[:danger] = "Veuillez vous inscrire/connecter avant de créer votre Event"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profil mis à jour"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

# Logs in the given user.
   def log_in(user)
     session[:user_id] = user.id
   end

# Returns the current logged-in user (if any).
def current_user
  @current_user ||= User.find_by(id: session[:user_id])
end

 # Returns true if the user is logged in, false otherwise.
   def logged_in?
     !current_user.nil?
   end

   def log_out
     session.delete(:user_id)
     @current_user = nil
     flash[:success] = "Good bye"
   end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<h1>Modifier votre évenement</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
      <%= form_for(@event) do |f| %>

  <br />
        <%= f.label :Titre %>
        <%= f.text_field :title, class: 'form-control' %>
  <br />
        <%= f.label :Description %>
        <%= f.text_area :description, class: 'form-control' %>
  <br />
        <%= f.label :"Date de l'event" %>
  <br />
        <%= f.date_field :date, class: 'form-control' %>
  <br />
        <%= f.label :"Lieu" %>
        <%= f.text_field :place, class: 'form-control' %>
  <br>
        <%= f.submit "Modifier votre event", class: "btn btn-primary" %>
        <%= link_to("Supprimer l'Event", event_path, method: :delete, class: "btn btn-danger") %>

    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<strong><h3>Tous les Events</h3></strong>

  <% if !logged_in? %>
    <h2>Connectez vous pour plus d'informations sur les Events !</h2>
    <h2>
    <%= link_to("SignUp", signup_path, class: "btn btn-success" ) %>
    <%= link_to("Log In", login_path, class: "btn btn-primary" ) %>
  </h2>
  <% end %>
<br>

<table class="table table-hover">
  <tr>
    <th>Titre</th>
    <th>Description</th>
    <th>Date</th>
    <th>Lieu</th>
    <% if logged_in? %>
      <th>créé par</th>
      <th>Action</th>
      <th>Participants</th>
    <%end%>
  </tr>

  <%@events.each do |event|%>
    <tr>
      <td><%= event.title %></td>
      <td><%= event.description %></td>
      <td><%= event.date.strftime("%d/%m/%Y") %></td>     <!-- source : https://www.ruby-forum.com/topic/82271 -->
      <td><%= event.place %></td>
      <% if logged_in? %>
        <td><%=link_to(event.creator.name, user_path(event.creator.id))%></td>
        <td><%=link_to("Voir", event_path(event.id))%></td>
        <td><%=link_to(event.attendees.size, event_path(event.creator.id))%></td>
      <% end %>
    </tr>
  <%end%>
</table>

app/views/events/new.html.erb
<h1>Votre évenement</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
      <%= form_for(@event) do |f| %>

  <br />
        <%= f.label :Titre %>
        <%= f.text_field :title, class: 'form-control' %>
  <br />
        <%= f.label :Description %>
        <%= f.text_area :description, class: 'form-control' %>
  <br />
        <%= f.label :"Date de l'event" %>
  <br />
        <%= f.date_field :date, class: 'form-control' %>
  <br />
  <br />
        <%= f.label :"Lieu" %>
        <%= f.text_field :place, class: 'form-control' %>


        <br><br>
        <%= f.submit "Créer votre event", class: "btn btn-success" %>
      <% end %>

  </div>
</div>

app/views/events/show.html.erb
<div class="row">

    <section class="user_info">
      <div class="Event-creator">
        <h4>Evenement créé par <%= link_to(@event.creator.name, user_path(@event.creator.id))%></h4>
      </div>
      <h1><%= @event.title %></h1>
    </section>

    <div class="event_description">
      <h2><%= @event.description %></h2>
    </div>

    <h3>L'évènement aura lieu à <%= @event.place %></h3>
    <h3> Le <%= @event.date.strftime("%d/%m/%Y") %> </h3>

    <br />

    <%  if @event.creator.id == current_user.id %>
      <%= link_to "Modifier", edit_event_path, class: "btn btn-lg btn-primary" %>
      <%= link_to "Supprimer", event_path, method: :delete, class: "btn btn-danger" %>
    <%end%>
    <% if @event.attendees.include? current_user %>
      <%= link_to "Ne plus participer", unfollow_path, class: "btn btn-lg btn-danger" %>
    <% else %>
      <%= link_to "Participer", subscribe_path, class: "btn btn-lg btn-success" %>
    <% end %>
<br>

    <h2>Liste des participants à l'Event</h2>

    <table class="table table-hover">
      <tr>
        <th>Nom</th>
        <th>email</th>
        <th>Profil</th>
      </tr>

      <%@event.attendees.each do |attendee|%>
        <tr>
          <td><%= attendee.name %></td>
          <td><%= attendee.email %></td>
          <td> <%= link_to('Voir le profil', user_path(attendee)) %> </td>
        </tr>
      <%end%>
    </table>

</div>
<div class="Retour_index">
  <%= link_to("Retour aux Events", events_path, class: "btn btn-lg btn-info" )%>
</div>

app/views/events/showattendees.html.erb
<h1>Liste des participants à l'Event</h1>
<h2>event.name</h2>

<table class="table table-hover">
  <tr>
    <th>Nom</th>
    <th>email</th>
  </tr>

  <%@event.attendees.each do |attendee|%>
    <tr>
      <td><%= attendee.name %></td>
      <td><%= attendee.email %></td>
    </tr>
  <%end%>
</table>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by <a href="https://github.com/SebastienDvx">Sébastien Devaux</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help", '#' %></li>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "EventBrite", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Les Events", all_events_path %></li>

        <% if logged_in? %>
          <li><%= link_to "Créer votre Event", new_event_path %></li>
        <% else %>
          <li><%= link_to "Créer votre Event", signup_path %></li>
        <% end %>

        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name%> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= "Connexion" %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Sign Up", signup_path %></li>
            <li><%= link_to "Log in", login_path %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventBrite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <%= render 'layouts/header' %>
    <div class='container'>
      <% flash.each do |type, message| %>
      <div class="alert alert-<%= type %>"><%= message %>
      <% end %>
    </div>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>


</html>

app/views/static_pages/home.html.erb
<% if !logged_in? %>

<div class="center jumbotron">
<h1>Bienvenue</h1>
<h2>Chez EventBrite, on se charge de vous trouver tous les évenements dont vous revez.</h2>
<h2>Vous pouvez dès à présent consulter la liste des Event disponible à ce jour</h2>
<h2>Pour une utilisation optimale, nous vous invitons à vous connecter ! :) </h2>
<p>
  Veuillez vous connecter <%= link_to("Login .", login_path, class: "btn btn-primary" ) %>
</p>
<p>
  Sinon, créez un compte <%= link_to("SignUp", signup_path, class: "btn btn-success" ) %>
</p>
<p>
  Liste de tous les Events <%= link_to("Les Events ! ", events_path, class: "btn btn-info")%>
</p>
</div>
<% else %>
  <div class="center jumbotron">
  <h1>Bienvenue </h1>
  <h2>Chez EventBrite, on se charge de vous trouver tous les évenements dont vous revez.</h2>
  <p>
    Rendez-vous aux Events <%= link_to("Les Events ! ", events_path, class: "btn btn-info")%>
  </p>

<% end %>

app/views/users/edit.html.erb
<h1>Mise à jour du profil</h1>

<div class="row">
  <div class="col-md-6">
    <%= form_for(current_user) do |f| %>
    
      <p>
        <%= f.label :name %>
      </p>
        <%= f.text_field :name, class: 'form-control' %>
      <p>
        <%= f.label :email %>
      </p>
        <%= f.text_field :email, class: 'form-control' %>
      <p>
        <%= f.label :password %>
      </p>
        <%= f.password_field :password, class: 'form-control' %>
      <p>
        <%= f.label :password_confirmation, "Confirmation" %>
      </p>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

      <br><br>

      <%= f.submit "Modifier les informations", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Identification</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>

      <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@user.errors.count, "erreur") %> empêche la sauvegarde
              de ce formulaire :
            </h2>
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      <p>
        <%= f.label :name %>
      </p>
        <%= f.text_field :name, class: 'form-control' %>
      <p>
      <p>
        <%= f.label :email %>
      </p>
        <%= f.text_field :email, class: 'form-control' %>
      <p>
        <%= f.label :password %>
      </p>
        <%= f.password_field :password, class: 'form-control' %>
      <p>
        <%= f.label :password_confirmation, "Confirmation" %>
      </p>
        <%= f.password_field :password_confirmation, class: 'form-control' %>


        <br><br>
        <%= f.submit "Sign Up", class: "btn btn-primary" %>
      <% end %>
      <p>
        Déjà inscrit? Connectez-vous <%= link_to("ici", login_path ) %>
      </p>
  </div>
</div>

app/views/users/show.html.erb
<!-- <h2>User Profile Page</h2> -->

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
      	<%= @user.name %>
      </h1>
      <p> <%= @user.email %>
      <%  if @user.id == current_user.id %>
        <p> <%= link_to('Modifier',  edit_user_path, class: "btn btn-lg btn-primary") %> </p>
      <%end%>
    </section>
  </aside>
</div>

<h2> Evénements organisés </h2>

      <table class="table table-hover">
  		<tr>
	    	<th>Nom de l'événement</th>
	    	<th>Date</th>
	    	<th>Lieu</th>
	   		<th></th>
	   		<th></th>
 	 	 </tr>


     <% @user.created_events.each do |event| %>
   		<tr>
   		<td> <%= event.title %> </td>
   		<td> <%= event.date.strftime("%d/%m/%Y") %> </td>      <!-- source : https://www.ruby-forum.com/topic/82271 -->
   		<td> <%= event.place %> </td>
   		<td> <%= link_to('Afficher', event_path(event)) %> </td>
      <%  if @user.id == current_user.id %>
   		 <td> <%= link_to('Modifier Event', edit_event_path(event)) %> </td>
      <%end%>
   		</tr>
   		<% end %>
    </table>

<br>

<h2>
  Events auxquels
  <% if @user.id == current_user.id%>
      <%="vous participez"%>
  <%else%>
    <%="il participe"%>
  <% end %>
</h2>

  <table class="table table-hover">
	<tr>
  	<th>Nom de l'événement</th>
  	<th>Date</th>
  	<th>Lieu</th>
 		<th></th>
 		<th></th>
 	 </tr>

 <% @user.attended_events.each do |event| %>
   <% if event.date > Date.today %>
   		<tr>
     		<td> <%= event.title %> </td>
     		<td> <%= event.date.strftime("%d/%m/%Y")  %> </td>     <!-- source : https://www.ruby-forum.com/topic/82271 -->
     		<td> <%= event.place  %> </td>
     		<td> <%= link_to('Afficher', event_path(event)) %> </td>

   		</tr>
    <% end %>
 	<% end %>
</table>

<br>

<h2>
  Events passés auxquels
  <% if @user.id == current_user.id%>
      <%="vous avez participez"%>
  <%else%>
    <%="il a participe"%>
  <% end %>
</h2>
  <table class="table table-hover">
		<tr>
    	<th>Nom de l'événement</th>
    	<th>Date</th>
    	<th>Lieu</th>
   		<th></th>
   		<th></th>
	 	 </tr>


   <% @user.attended_events.each do |event| %>
     <% if event.date < Date.today %>
   		<tr>
        <td> <%= event.title %> </td>
        <td> <%= event.date.strftime("%d/%m/%Y") %> </td>   <!-- source : https://www.ruby-forum.com/topic/82271 -->
        <td> <%= event.place  %> </td>
   		</tr>
      <% end %>
 		<% end %>
  </table>